### ISSUE TITLE
Anything wrong with these stats ?

### ISSUE THREAD

**Issue by phwuil** [conda-incubator/condastats#22] opened 2024-06-02 06:05 UTC
* condastats version: 1.2.1
* Python version: 3.12.3
* Operating System: manjaro

### Description

condastats shows an exponential increase in downloads over the last few months. While we're confident in the quality of our package ;-), this seems unrealistic and, in any case, unexpected (*100 between 2023/12 and 2024/05 !).

Do you have any idea why these variations are occurring?

### What I Did

`condastats overall pyagrum  --monthly`
```
[...]
          2023-08      2484
          2023-09      2433
          2023-10      4560
          2023-11      3154
          2023-12      1114
          2024-01      2829
          2024-02      2812
          2024-03     12573
          2024-04     66098
          2024-05    110944
```

Thank you for any hints, explanation or information on this subject

**Comment by mglisse** [comment] 2024-06-03 08:29
I am seeing the same explosion with pretty much any random package I try. It also seems to contradict what https://anaconda.org/conda-forge/XXX shows (monthly download much higher than the difference between the total now and the total 6 months ago).

**Comment by mglisse** [comment] 2024-06-05 10:19
https://github.com/ContinuumIO/anaconda-package-data/issues/45#issuecomment-2147788870

**Comment by jakirkham** [comment] 2024-06-25 00:51
@jezdez would it make sense to transfer this to https://github.com/ContinuumIO/anaconda-package-data ?

**Comment by jakirkham** [comment] 2024-07-16 01:59
Closing as duplicate of issue: https://github.com/ContinuumIO/anaconda-package-data/issues/52

**Closed by jakirkham** 2024-07-16 01:59 UTC
